<?php

declare(strict_types=1);

namespace IMedia\Menu\Icons\Providers;

use IMedia\Menu\Contracts\IconProvider;

final class DashiconsProvider implements IconProvider
{
    public function id(): string
    {
        return 'dashicons';
    }

    public function name(): string
    {
        return __('Dashicons', 'imedia-menu');
    }

    public function getIcon(string $identifier): string
    {
        return sprintf(
            '<span class="dashicons dashicons-%s" aria-hidden="true"></span>',
            esc_attr($identifier)
        );
    }

    public function getAvailableIcons(): array
    {
        return [
            'admin-home'     => __('Home', 'imedia-menu'),
            'admin-users'    => __('Users', 'imedia-menu'),
            'admin-settings' => __('Settings', 'imedia-menu'),
            'admin-tools'    => __('Tools', 'imedia-menu'),
            'admin-appearance' => __('Appearance', 'imedia-menu'),
            'menu'           => __('Menu', 'imedia-menu'),
            'admin-post'     => __('Post', 'imedia-menu'),
            'admin-page'     => __('Page', 'imedia-menu'),
            'admin-media'    => __('Media', 'imedia-menu'),
            'admin-links'    => __('Links', 'imedia-menu'),
            'admin-comments' => __('Comments', 'imedia-menu'),
            'admin-plugins'  => __('Plugins', 'imedia-menu'),
            'admin-network'  => __('Network', 'imedia-menu'),
            'admin-generic'  => __('Generic', 'imedia-menu'),
            'admin-collapse' => __('Collapse', 'imedia-menu'),
            'search'         => __('Search', 'imedia-menu'),
            'star-filled'    => __('Star Filled', 'imedia-menu'),
            'star-empty'     => __('Star Empty', 'imedia-menu'),
            'star-half'      => __('Star Half', 'imedia-menu'),
            'heart'          => __('Heart', 'imedia-menu'),
            'info'           => __('Info', 'imedia-menu'),
            'warning'        => __('Warning', 'imedia-menu'),
            'cart'           => __('Cart', 'imedia-menu'),
            'feedback'       => __('Feedback', 'imedia-menu'),
            'phone'          => __('Phone', 'imedia-menu'),
            'email'          => __('Email', 'imedia-menu'),
            'location'       => __('Location', 'imedia-menu'),
            'calendar'       => __('Calendar', 'imedia-menu'),
            'clock'          => __('Clock', 'imedia-menu'),
            'download'       => __('Download', 'imedia-menu'),
            'upload'         => __('Upload', 'imedia-menu'),
            'external'       => __('External', 'imedia-menu'),
            'arrow-up'       => __('Arrow Up', 'imedia-menu'),
            'arrow-down'     => __('Arrow Down', 'imedia-menu'),
            'arrow-left'     => __('Arrow Left', 'imedia-menu'),
            'arrow-right'    => __('Arrow Right', 'imedia-menu'),
            'plus'           => __('Plus', 'imedia-menu'),
            'minus'          => __('Minus', 'imedia-menu'),
            'yes'            => __('Yes/Check', 'imedia-menu'),
            'no'             => __('No/X', 'imedia-menu'),
            'chart-bar'      => __('Chart Bar', 'imedia-menu'),
            'chart-line'     => __('Chart Line', 'imedia-menu'),
            'chart-pie'      => __('Chart Pie', 'imedia-menu'),
            'portfolio'      => __('Portfolio', 'imedia-menu'),
            'book'           => __('Book', 'imedia-menu'),
            'book-alt'       => __('Book Alt', 'imedia-menu'),
            'tag'            => __('Tag', 'imedia-menu'),
            'tagcloud'       => __('Tag Cloud', 'imedia-menu'),
            'category'       => __('Category', 'imedia-menu'),
            'format-image'   => __('Image', 'imedia-menu'),
            'format-video'   => __('Video', 'imedia-menu'),
            'format-audio'   => __('Audio', 'imedia-menu'),
            'format-chat'    => __('Chat', 'imedia-menu'),
            'format-status'  => __('Status', 'imedia-menu'),
            'format-quote'   => __('Quote', 'imedia-menu'),
            'format-gallery' => __('Gallery', 'imedia-menu'),
            'text'           => __('Text', 'imedia-menu'),
            'editor-bold'    => __('Bold', 'imedia-menu'),
            'editor-italic'  => __('Italic', 'imedia-menu'),
            'editor-ul'      => __('Unordered List', 'imedia-menu'),
            'editor-ol'      => __('Ordered List', 'imedia-menu'),
            'editor-code'    => __('Code', 'imedia-menu'),
            'editor-link'    => __('Link', 'imedia-menu'),
            'editor-textcolor' => __('Text Color', 'imedia-menu'),
            'visibility'     => __('Visibility', 'imedia-menu'),
            'lock'           => __('Lock', 'imedia-menu'),
            'unlock'         => __('Unlock', 'imedia-menu'),
            'businessman'    => __('Businessman', 'imedia-menu'),
            'businessperson' => __('Businessperson', 'imedia-menu'),
            'products'       => __('Products', 'imedia-menu'),
            'groups'         => __('Groups', 'imedia-menu'),
            'id'             => __('ID', 'imedia-menu'),
            'id-alt'         => __('ID Alt', 'imedia-menu'),
            'list-view'      => __('List View', 'imedia-menu'),
            'grid-view'      => __('Grid View', 'imedia-menu'),
            'index-card'     => __('Index Card', 'imedia-menu'),
            'lightbulb'      => __('Lightbulb', 'imedia-menu'),
            'money'          => __('Money', 'imedia-menu'),
            'palmtree'       => __('Palm Tree', 'imedia-menu'),
            'screenoptions'  => __('Screen Options', 'imedia-menu'),
            'tablet'         => __('Tablet', 'imedia-menu'),
            'smartphone'     => __('Smartphone', 'imedia-menu'),
            'laptop'         => __('Laptop', 'imedia-menu'),
            'desktop'        => __('Desktop', 'imedia-menu'),
            'art'            => __('Art', 'imedia-menu'),
            'awards'         => __('Awards', 'imedia-menu'),
            'backup'         => __('Backup', 'imedia-menu'),
            'building'       => __('Building', 'imedia-menu'),
            'car'            => __('Car', 'imedia-menu'),
            'clipboard'      => __('Clipboard', 'imedia-menu'),
            'controls-play'  => __('Play', 'imedia-menu'),
            'controls-pause' => __('Pause', 'imedia-menu'),
            'controls-forward' => __('Forward', 'imedia-menu'),
            'controls-back'  => __('Back', 'imedia-menu'),
            'controls-repeat' => __('Repeat', 'imedia-menu'),
            'controls-volumeon' => __('Volume On', 'imedia-menu'),
            'controls-volumeoff' => __('Volume Off', 'imedia-menu'),
            'dismiss'        => __('Dismiss', 'imedia-menu'),
            'edit'           => __('Edit', 'imedia-menu'),
            'ellipsis'       => __('Ellipsis', 'imedia-menu'),
            'excerpt-view'   => __('Excerpt View', 'imedia-menu'),
            'exit'           => __('Exit', 'imedia-menu'),
            'flag'           => __('Flag', 'imedia-menu'),
            'format-aside'   => __('Aside', 'imedia-menu'),
            'image-crop'     => __('Crop', 'imedia-menu'),
            'image-flip-horizontal' => __('Flip Horizontal', 'imedia-menu'),
            'image-flip-vertical' => __('Flip Vertical', 'imedia-menu'),
            'image-rotate'   => __('Rotate', 'imedia-menu'),
            'images-alt'     => __('Images Alt', 'imedia-menu'),
            'images-alt2'    => __('Images Alt 2', 'imedia-menu'),
            'layout'         => __('Layout', 'imedia-menu'),
            'leftright'      => __('Left/Right', 'imedia-menu'),
            'marker'         => __('Marker', 'imedia-menu'),
            'media-archive'  => __('Archive', 'imedia-menu'),
            'media-audio'    => __('Audio', 'imedia-menu'),
            'media-code'     => __('Code', 'imedia-menu'),
            'media-default'  => __('Default', 'imedia-menu'),
            'media-document' => __('Document', 'imedia-menu'),
            'media-interactive' => __('Interactive', 'imedia-menu'),
            'media-spreadsheet' => __('Spreadsheet', 'imedia-menu'),
            'media-text'     => __('Text', 'imedia-menu'),
            'media-video'    => __('Video', 'imedia-menu'),
            'migrate'        => __('Migrate', 'imedia-menu'),
            'move'           => __('Move', 'imedia-menu'),
            'networking'     => __('Networking', 'imedia-menu'),
            'performance'    => __('Performance', 'imedia-menu'),
            'playlist-audio' => __('Playlist Audio', 'imedia-menu'),
            'playlist-video' => __('Playlist Video', 'imedia-menu'),
            'pressthis'      => __('Press This', 'imedia-menu'),
            'randomize'      => __('Randomize', 'imedia-menu'),
            'redo'           => __('Redo', 'imedia-menu'),
            'rest-api'       => __('REST API', 'imedia-menu'),
            'rss'            => __('RSS', 'imedia-menu'),
            'schedule'       => __('Schedule', 'imedia-menu'),
            'share'          => __('Share', 'imedia-menu'),
            'share-alt'      => __('Share Alt', 'imedia-menu'),
            'share-alt2'     => __('Share Alt 2', 'imedia-menu'),
            'shortcode'      => __('Shortcode', 'imedia-menu'),
            'slides'         => __('Slides', 'imedia-menu'),
            'sort'           => __('Sort', 'imedia-menu'),
            'sos'            => __('SOS', 'imedia-menu'),
            'store'          => __('Store', 'imedia-menu'),
            'superhero'      => __('Superhero', 'imedia-menu'),
            'superhero-alt'  => __('Superhero Alt', 'imedia-menu'),
            'testimonial'    => __('Testimonial', 'imedia-menu'),
            'tickets'        => __('Tickets', 'imedia-menu'),
            'tickets-alt'    => __('Tickets Alt', 'imedia-menu'),
            'translation'    => __('Translation', 'imedia-menu'),
            'trash'          => __('Trash', 'imedia-menu'),
            'universal-access' => __('Universal Access', 'imedia-menu'),
            'universal-access-alt' => __('Universal Access Alt', 'imedia-menu'),
            'update'         => __('Update', 'imedia-menu'),
            'update-alt'     => __('Update Alt', 'imedia-menu'),
            'vault'          => __('Vault', 'imedia-menu'),
            'video-alt'      => __('Video Alt', 'imedia-menu'),
            'video-alt2'     => __('Video Alt 2', 'imedia-menu'),
            'video-alt3'     => __('Video Alt 3', 'imedia-menu'),
            'welcome-widgets-menus' => __('Widgets/Menus', 'imedia-menu'),
            'wordpress'      => __('WordPress', 'imedia-menu'),
            'welcome-add-page' => __('Add Page', 'imedia-menu'),
            'welcome-comments' => __('Comments', 'imedia-menu'),
            'welcome-learn-more' => __('Learn More', 'imedia-menu'),
            'welcome-view-site' => __('View Site', 'imedia-menu'),
            'welcome-widgets' => __('Widgets', 'imedia-menu'),
            'welcome-write-blog' => __('Write Blog', 'imedia-menu'),
            'analytics'      => __('Analytics', 'imedia-menu'),
            'align-full-width' => __('Align Full Width', 'imedia-menu'),
            'align-pull-left' => __('Align Pull Left', 'imedia-menu'),
            'align-pull-right' => __('Align Pull Right', 'imedia-menu'),
            'align-wide'     => __('Align Wide', 'imedia-menu'),
            'block-default'  => __('Block Default', 'imedia-menu'),
            'button'         => __('Button', 'imedia-menu'),
            'cloud'          => __('Cloud', 'imedia-menu'),
            'cloud-saved'    => __('Cloud Saved', 'imedia-menu'),
            'cloud-upload'   => __('Cloud Upload', 'imedia-menu'),
            'columns'        => __('Columns', 'imedia-menu'),
            'cover-image'    => __('Cover Image', 'imedia-menu'),
            'embed-audio'    => __('Embed Audio', 'imedia-menu'),
            'embed-generic'  => __('Embed Generic', 'imedia-menu'),
            'embed-photo'    => __('Embed Photo', 'imedia-menu'),
            'embed-post'     => __('Embed Post', 'imedia-menu'),
            'embed-video'    => __('Embed Video', 'imedia-menu'),
            'heading'        => __('Heading', 'imedia-menu'),
            'html'           => __('HTML', 'imedia-menu'),
            'info-outline'   => __('Info Outline', 'imedia-menu'),
            'insert'         => __('Insert', 'imedia-menu'),
            'insert-after'   => __('Insert After', 'imedia-menu'),
            'insert-before'  => __('Insert Before', 'imedia-menu'),
            'remove'         => __('Remove', 'imedia-menu'),
            'saved'          => __('Saved', 'imedia-menu'),
            'spellcheck'     => __('Spellcheck', 'imedia-menu'),
            'sticky'         => __('Sticky', 'imedia-menu'),
            'table-col-before' => __('Table Col Before', 'imedia-menu'),
            'table-col-after' => __('Table Col After', 'imedia-menu'),
            'table-col-delete' => __('Table Col Delete', 'imedia-menu'),
            'table-row-before' => __('Table Row Before', 'imedia-menu'),
            'table-row-after' => __('Table Row After', 'imedia-menu'),
            'table-row-delete' => __('Table Row Delete', 'imedia-menu'),
            'tablet'         => __('Tablet', 'imedia-menu'),
            'tag'            => __('Tag', 'imedia-menu'),
            'tagcloud'       => __('Tagcloud', 'imedia-menu'),
            'tide'           => __('Tide', 'imedia-menu'),
            'undo'           => __('Undo', 'imedia-menu'),
            'align-center'   => __('Align Center', 'imedia-menu'),
            'align-left'     => __('Align Left', 'imedia-menu'),
            'align-right'    => __('Align Right', 'imedia-menu'),
            'align-none'     => __('Align None', 'imedia-menu'),
            'editor-aligncenter' => __('Align Center', 'imedia-menu'),
            'editor-alignleft' => __('Align Left', 'imedia-menu'),
            'editor-alignright' => __('Align Right', 'imedia-menu'),
            'editor-break'   => __('Break', 'imedia-menu'),
            'editor-code'    => __('Code', 'imedia-menu'),
            'editor-contract' => __('Contract', 'imedia-menu'),
            'editor-customchar' => __('Custom Character', 'imedia-menu'),
            'editor-expand'  => __('Expand', 'imedia-menu'),
            'editor-help'    => __('Help', 'imedia-menu'),
            'editor-indent'  => __('Indent', 'imedia-menu'),
            'editor-insertmore' => __('Insert More', 'imedia-menu'),
            'editor-kitchensink' => __('Kitchen Sink', 'imedia-menu'),
            'editor-ltr'     => __('LTR', 'imedia-menu'),
            'editor-ol'      => __('Ordered List', 'imedia-menu'),
            'editor-outdent' => __('Outdent', 'imedia-menu'),
            'editor-paragraph' => __('Paragraph', 'imedia-menu'),
            'editor-paste-text' => __('Paste Text', 'imedia-menu'),
            'editor-paste-word' => __('Paste Word', 'imedia-menu'),
            'editor-quote'   => __('Quote', 'imedia-menu'),
            'editor-removeformatting' => __('Remove Formatting', 'imedia-menu'),
            'editor-rtl'     => __('RTL', 'imedia-menu'),
            'editor-spellcheck' => __('Spellcheck', 'imedia-menu'),
            'editor-strikethrough' => __('Strikethrough', 'imedia-menu'),
            'editor-table'   => __('Table', 'imedia-menu'),
            'editor-textcolor' => __('Text Color', 'imedia-menu'),
            'editor-underline' => __('Underline', 'imedia-menu'),
            'editor-video'   => __('Video', 'imedia-menu'),
            'editor-wordpress' => __('WordPress', 'imedia-menu'),
        ];
    }
}
