<?php

declare(strict_types=1);

namespace IMedia\Menu\Fonts;

final class GoogleFontsProvider {

	private const WEIGHTS = array( 100, 200, 300, 400, 500, 600, 700, 800, 900 );

	private const SUBSETS = array(
		'latin'              => 'Latin',
		'latin-ext'          => 'Latin Extended',
		'cyrillic'           => 'Cyrillic',
		'cyrillic-ext'       => 'Cyrillic Extended',
		'greek'              => 'Greek',
		'greek-ext'          => 'Greek Extended',
		'vietnamese'         => 'Vietnamese',
		'arabic'             => 'Arabic',
		'devanagari'         => 'Devanagari',
		'bengali'            => 'Bengali',
		'hebrew'             => 'Hebrew',
		'thai'               => 'Thai',
		'korean'             => 'Korean',
		'japanese'           => 'Japanese',
		'chinese-simplified' => 'Chinese Simplified',
	);

	public static function getFonts(): array {
		$fonts = array(
			'ABeeZee',
			'Abel',
			'Abhaya Libre',
			'Abril Fatface',
			'Aclonica',
			'Acme',
			'Actor',
			'Adamina',
			'Advent Pro',
			'Aguafina Script',
			'Akaya Kanadaka',
			'Albert Sans',
			'Aldrich',
			'Alef',
			'Alegreya',
			'Alegreya Sans',
			'Alegreya Sans SC',
			'Aleo',
			'Alex Brush',
			'Alfa Slab One',
			'Alice',
			'Alike',
			'Allan',
			'Allerta',
			'Allison',
			'Almarai',
			'Alumni Sans',
			'Amaranth',
			'Amatic SC',
			'Amiri',
			'Amita',
			'Anaheim',
			'Andada Pro',
			'Andika',
			'Angkor',
			'Anonymous Pro',
			'Antic',
			'Antic Slab',
			'Anton',
			'Antonio',
			'Arapey',
			'Architects Daughter',
			'Archivo',
			'Archivo Black',
			'Archivo Narrow',
			'Aref Ruqaa',
			'Arimo',
			'Armata',
			'Arsenal',
			'Artifika',
			'Arvo',
			'Asap',
			'Asap Condensed',
			'Assistant',
			'Athiti',
			'Atkinson Hyperlegible',
			'Atomic Age',
			'Audiowide',
			'Averia Libre',
			'Averia Sans Libre',
			'Azeret Mono',
			'B612',
			'Bad Script',
			'Bai Jamjuree',
			'Bakbak One',
			'Baloo 2',
			'Balsamiq Sans',
			'Bangers',
			'Barlow',
			'Barlow Condensed',
			'Barlow Semi Condensed',
			'Basic',
			'Be Vietnam Pro',
			'Bebas Neue',
			'Belgrano',
			'Bellefair',
			'Bellota',
			'BenchNine',
			'Benne',
			'Berkshire Swash',
			'Besley',
			'Bevan',
			'Big Shoulders Display',
			'Big Shoulders Text',
			'BioRhyme',
			'Biryani',
			'Bitter',
			'Black Han Sans',
			'Black Ops One',
			'Blinker',
			'Bodoni Moda',
			'Bona Nova',
			'Bonheur Royale',
			'Boogaloo',
			'Bowlby One SC',
			'Brawler',
			'Bree Serif',
			'Brygada 1918',
			'Bubblegum Sans',
			'Buda',
			'Buenard',
			'Bungee',
			'Butcherman',
			'Cabin',
			'Cabin Condensed',
			'Cabin Sketch',
			'Caesar Dressing',
			'Cairo',
			'Caladea',
			'Calistoga',
			'Calligraffitti',
			'Cambay',
			'Cambo',
			'Candal',
			'Cantarell',
			'Cantata One',
			'Capriola',
			'Cardo',
			'Carrois Gothic',
			'Carter One',
			'Catamaran',
			'Caudex',
			'Caveat',
			'Caveat Brush',
			'Cedarville Cursive',
			'Chakra Petch',
			'Changa',
			'Changa One',
			'Charm',
			'Charmonman',
			'Cherry Swash',
			'Chewy',
			'Chicle',
			'Chivo',
			'Chonburi',
			'Cinzel',
			'Cinzel Decorative',
			'Clicker Script',
			'Coda',
			'Codystar',
			'Coiny',
			'Combo',
			'Comfortaa',
			'Comic Neue',
			'Coming Soon',
			'Commissioner',
			'Concert One',
			'Condiment',
			'Contrail One',
			'Convergence',
			'Cookie',
			'Copse',
			'Corben',
			'Cormorant',
			'Cormorant Garamond',
			'Cormorant Infant',
			'Cormorant SC',
			'Cormorant Unicase',
			'Courgette',
			'Courier Prime',
			'Cousine',
			'Coustard',
			'Covered By Your Grace',
			'Creepster',
			'Crete Round',
			'Crimson Pro',
			'Crimson Text',
			'Croissant One',
			'Cuprum',
			'DM Mono',
			'DM Sans',
			'DM Serif Display',
			'DM Serif Text',
			'Damion',
			'Dancing Script',
			'Darker Grotesque',
			'David Libre',
			'Dawning of a New Day',
			'Days One',
			'Della Respira',
			'Denk One',
			'Devonshire',
			'Didact Gothic',
			'Diplomata',
			'Do Hyeon',
			'Dokdo',
			'Domine',
			'Donegal One',
			'Doppio One',
			'Dorsa',
			'Dosis',
			'Dr Sugiyama',
			'Duru Sans',
			'DynaPuff',
			'EB Garamond',
			'Eagle Lake',
			'Eater',
			'Economica',
			'Eczar',
			'El Messiri',
			'Electrolize',
			'Elsie',
			'Emilys Candy',
			'Encode Sans',
			'Encode Sans Condensed',
			'Enriqueta',
			'Ephesis',
			'Epilogue',
			'Erica One',
			'Esteban',
			'Euphoria Script',
			'Ewert',
			'Exo',
			'Exo 2',
			'Expletus Sans',
			'Explora',
			'Fahkwang',
			'Familjen Grotesk',
			'Fanwood Text',
			'Farro',
			'Farsan',
			'Fascinate',
			'Faster One',
			'Fauna One',
			'Faustina',
			'Federant',
			'Federo',
			'Felipa',
			'Fenix',
			'Figtree',
			'Finger Paint',
			'Fira Code',
			'Fira Mono',
			'Fira Sans',
			'Fira Sans Condensed',
			'Fira Sans Extra Condensed',
			'Fjalla One',
			'Fjord One',
			'Flamenco',
			'Flavors',
			'Fondamento',
			'Fontdiner Swanky',
			'Forum',
			'Francois One',
			'Frank Ruhl Libre',
			'Fraunces',
			'Freckle Face',
			'Fredericka the Great',
			'Fredoka',
			'Fredoka One',
			'Fresca',
			'Frijole',
			'Fruktur',
			'Fugaz One',
			'GFS Didot',
			'GFS Neohellenic',
			'Gabriela',
			'Gaegu',
			'Gafata',
			'Galada',
			'Gelasio',
			'Gentium Book Basic',
			'Gentium Book Plus',
			'Gentium Plus',
			'Geo',
			'Georama',
			'Germania One',
			'Gideon Roman',
			'Gilda Display',
			'Girassol',
			'Give You Glory',
			'Glass Antiqua',
			'Glegoo',
			'Gloria Hallelujah',
			'Glory',
			'Gluten',
			'Goblin One',
			'Gochi Hand',
			'Goldman',
			'Gorditas',
			'Gothic A1',
			'Gotu',
			'Goudy Bookletter 1911',
			'Graduate',
			'Grand Hotel',
			'Grandstander',
			'Gravitas One',
			'Great Vibes',
			'Grenze',
			'Grenze Gotisch',
			'Griffy',
			'Gruppo',
			'Gudea',
			'Gugi',
			'Gupter',
			'Gurajada',
			'Habibi',
			'Hahmlet',
			'Halant',
			'Hammersmith One',
			'Handlee',
			'Hanuman',
			'Happy Monkey',
			'Harmattan',
			'Headland One',
			'Heebo',
			'Henny Penny',
			'Hepta Slab',
			'Herr Von Muellerhoff',
			'Hind',
			'Hind Guntur',
			'Hind Madurai',
			'Hind Siliguri',
			'Hind Vadodara',
			'Holtwood One SC',
			'Homemade Apple',
			'Homenaje',
			'IBM Plex Mono',
			'IBM Plex Sans',
			'IBM Plex Sans Condensed',
			'IBM Plex Serif',
			'Ibarra Real Nova',
			'Iceberg',
			'Iceland',
			'Imbue',
			'Imprima',
			'Inconsolata',
			'Inder',
			'Indie Flower',
			'Inika',
			'Inknut Antiqua',
			'Inria Sans',
			'Inria Serif',
			'Inter',
			'Irish Grover',
			'Istok Web',
			'Italiana',
			'Italianno',
			'Itim',
			'Jaldi',
			'JetBrains Mono',
			'Jim Nightshade',
			'Jockey One',
			'Jolly Lodger',
			'Jomhuria',
			'Josefin Sans',
			'Josefin Slab',
			'Jost',
			'Joti One',
			'Jua',
			'Judson',
			'Julee',
			'Julius Sans One',
			'Junge',
			'Jura',
			'Just Another Hand',
			'Just Me Again Down Here',
			'K2D',
			'Kadwa',
			'Kalam',
			'Kameron',
			'Kanit',
			'Kantumruy',
			'Kantumruy Pro',
			'Karantina',
			'Karla',
			'Karma',
			'Katibeh',
			'Kaushan Script',
			'Kavivanar',
			'Kavoon',
			'Keania One',
			'Kelly Slab',
			'Kenia',
			'Khand',
			'Khmer',
			'Khula',
			'Kite One',
			'Kiwi Maru',
			'Klee One',
			'Knewave',
			'KoHo',
			'Kodchasan',
			'Koh Santepheap',
			'Kosugi',
			'Kosugi Maru',
			'Kotta One',
			'Koulen',
			'Kranky',
			'Kreon',
			'Kristi',
			'Krona One',
			'Krub',
			'Kufam',
			'Kulim Park',
			'Kumar One',
			'Kumbh Sans',
			'Kurale',
			'La Belle Aurore',
			'Lacquer',
			'Laila',
			'Lalezar',
			'Lancelot',
			'Langar',
			'Lateef',
			'Lato',
			'League Gothic',
			'League Spartan',
			'Leckerli One',
			'Ledger',
			'Lekton',
			'Lemon',
			'Lemonada',
			'Lexend',
			'Lexend Deca',
			'Lexend Exa',
			'Lexend Mega',
			'Lexend Peta',
			'Lexend Tera',
			'Lexend Zetta',
			'Libre Baskerville',
			'Libre Bodoni',
			'Libre Caslon Text',
			'Libre Franklin',
			'Licorice',
			'Life Savers',
			'Lilita One',
			'Lily Script One',
			'Limelight',
			'Linden Hill',
			'Literata',
			'Livvic',
			'Lobster',
			'Lobster Two',
			'Londrina Solid',
			'Long Cang',
			'Lora',
			'Love Ya Like A Sister',
			'Loved by the King',
			'Luckiest Guy',
			'Lusitana',
			'Lustria',
			'M PLUS 1',
			'M PLUS 1p',
			'M PLUS 2',
			'M PLUS Rounded 1c',
			'Ma Shan Zheng',
			'Macondo',
			'Macondo Swash Caps',
			'Mada',
			'Magra',
			'Maiden Orange',
			'Maitree',
			'Major Mono Display',
			'Mako',
			'Mali',
			'Mallanna',
			'Mandali',
			'Manjari',
			'Manrope',
			'Mansalva',
			'Manuale',
			'Marcellus',
			'Marcellus SC',
			'Marck Script',
			'Margarine',
			'Markazi Text',
			'Marko One',
			'Marmelad',
			'Martel',
			'Martel Sans',
			'Marvel',
			'Mate',
			'Mate SC',
			'Maven Pro',
			'McLaren',
			'Meddon',
			'MedievalSharp',
			'Medula One',
			'Meera Inimai',
			'Megrim',
			'Meie Script',
			'Merienda',
			'Merienda One',
			'Merriweather',
			'Merriweather Sans',
			'Metal',
			'Metal Mania',
			'Metamorphous',
			'Metrophobic',
			'Michroma',
			'Milonga',
			'Miltonian',
			'Miltonian Tattoo',
			'Mina',
			'Miniver',
			'Miriam Libre',
			'Mirza',
			'Miss Fajardose',
			'Mitr',
			'Modak',
			'Modern Antiqua',
			'Mogra',
			'Molengo',
			'Monda',
			'Monofett',
			'Monoton',
			'Monsieur La Doulaise',
			'Montaga',
			'Montagu Slab',
			'MonteCarlo',
			'Montez',
			'Montserrat',
			'Montserrat Alternates',
			'Montserrat Subrayada',
			'Moul',
			'Moulpali',
			'Mountains of Christmas',
			'Mouse Memoirs',
			'Mr Bedfort',
			'Mr Dafoe',
			'Mr De Haviland',
			'Mrs Saint Delafield',
			'Mrs Sheppards',
			'Ms Madi',
			'Mukta',
			'Mukta Mahee',
			'Mukta Malar',
			'Mukta Vaani',
			'Mulish',
			'Murecho',
			'MuseoModerno',
			'Mystery Quest',
			'NTR',
			'Nanum Brush Script',
			'Nanum Gothic',
			'Nanum Gothic Coding',
			'Nanum Myeongjo',
			'Nanum Pen Script',
			'Neonderthaw',
			'Nerko One',
			'Neucha',
			'Neuton',
			'New Rocker',
			'News Cycle',
			'Newsreader',
			'Niconne',
			'Niramit',
			'Nixie One',
			'Nobile',
			'Nokora',
			'Norican',
			'Nosifer',
			'Notable',
			'Nothing You Could Do',
			'Noticia Text',
			'Noto Sans',
			'Noto Sans Display',
			'Noto Sans HK',
			'Noto Sans JP',
			'Noto Sans KR',
			'Noto Sans Mono',
			'Noto Sans SC',
			'Noto Sans TC',
			'Noto Serif',
			'Noto Serif Display',
			'Noto Serif JP',
			'Noto Serif KR',
			'Noto Serif SC',
			'Noto Serif TC',
			'Nova Cut',
			'Nova Flat',
			'Nova Mono',
			'Nova Oval',
			'Nova Round',
			'Nova Script',
			'Nova Slim',
			'Nova Square',
			'Numans',
			'Nunito',
			'Nunito Sans',
			'Odibee Sans',
			'Odor Mean Chey',
			'Offside',
			'Oi',
			'Old Standard TT',
			'Oldenburg',
			'Oleo Script',
			'Oleo Script Swash Caps',
			'Open Sans',
			'Oranienbaum',
			'Orbitron',
			'Oregano',
			'Orienta',
			'Original Surfer',
			'Oswald',
			'Outfit',
			'Over the Rainbow',
			'Overlock',
			'Overlock SC',
			'Overpass',
			'Overpass Mono',
			'Ovo',
			'Oxanium',
			'Oxygen',
			'Oxygen Mono',
			'PT Mono',
			'PT Sans',
			'PT Sans Caption',
			'PT Sans Narrow',
			'PT Serif',
			'PT Serif Caption',
			'Pacifico',
			'Padauk',
			'Palanquin',
			'Palanquin Dark',
			'Pangolin',
			'Paprika',
			'Parisienne',
			'Passero One',
			'Passion One',
			'Pathway Gothic One',
			'Patrick Hand',
			'Patrick Hand SC',
			'Pattaya',
			'Patua One',
			'Pavanam',
			'Paytone One',
			'Peddana',
			'Peralta',
			'Permanent Marker',
			'Petit Formal Script',
			'Petrona',
			'Philosopher',
			'Piazzolla',
			'Piedra',
			'Pinyon Script',
			'Pirata One',
			'Plaster',
			'Play',
			'Playball',
			'Playfair Display',
			'Playfair Display SC',
			'Plus Jakarta Sans',
			'Podkova',
			'Poiret One',
			'Poller One',
			'Poly',
			'Pompiere',
			'Pontano Sans',
			'Poor Story',
			'Poppins',
			'Port Lligat Sans',
			'Port Lligat Slab',
			'Potta One',
			'Pragati Narrow',
			'Prata',
			'Preahvihear',
			'Press Start 2P',
			'Pridi',
			'Princess Sofia',
			'Prociono',
			'Prompt',
			'Prosto One',
			'Proza Libre',
			'Public Sans',
			'Puritan',
			'Purple Purse',
			'Quando',
			'Quantico',
			'Quattrocento',
			'Quattrocento Sans',
			'Questrial',
			'Quicksand',
			'Quintessential',
			'Qwigley',
			'Racing Sans One',
			'Radio Canada',
			'Radley',
			'Rajdhani',
			'Rakkas',
			'Raleway',
			'Raleway Dots',
			'Ramabhadra',
			'Ramaraja',
			'Rambla',
			'Rammetto One',
			'Rampart One',
			'Ranchers',
			'Rancho',
			'Ranga',
			'Rasa',
			'Rationale',
			'Ravi Prakash',
			'Readex Pro',
			'Recursive',
			'Red Hat Display',
			'Red Hat Mono',
			'Red Hat Text',
			'Red Rose',
			'Reenie Beanie',
			'Reggae One',
			'Revalia',
			'Rhodium Libre',
			'Ribeye',
			'Ribeye Marrow',
			'Righteous',
			'Risque',
			'Road Rage',
			'Roboto',
			'Roboto Condensed',
			'Roboto Flex',
			'Roboto Mono',
			'Roboto Serif',
			'Roboto Slab',
			'Rochester',
			'Rock Salt',
			'RocknRoll One',
			'Rokkitt',
			'Romanesco',
			'Ropa Sans',
			'Rosario',
			'Rosarivo',
			'Rouge Script',
			'Rowdies',
			'Rozha One',
			'Rubik',
			'Rubik Bubbles',
			'Rubik Glitch',
			'Rubik Iso',
			'Rubik Mono One',
			'Rubik Moonrocks',
			'Ruda',
			'Rufina',
			'Ruge Boogie',
			'Ruluko',
			'Rum Raisin',
			'Ruslan Display',
			'Russo One',
			'Ruthie',
			'Rye',
			'STIX Two Text',
			'Sacramento',
			'Sahitya',
			'Sail',
			'Saira',
			'Saira Condensed',
			'Saira Extra Condensed',
			'Saira Semi Condensed',
			'Saira Stencil One',
			'Salsa',
			'Sanchez',
			'Sancreek',
			'Sansita',
			'Sansita Swashed',
			'Sarabun',
			'Sarala',
			'Sarina',
			'Sarpanch',
			'Satisfy',
			'Sawarabi Gothic',
			'Sawarabi Mincho',
			'Scada',
			'Scheherazade New',
			'Schoolbell',
			'Seaweed Script',
			'Secular One',
			'Sedgwick Ave',
			'Sedgwick Ave Display',
			'Sen',
			'Sevillana',
			'Shadows Into Light',
			'Shadows Into Light Two',
			'Shalimar',
			'Shanti',
			'Share',
			'Share Tech',
			'Share Tech Mono',
			'Shippori Mincho',
			'Shojumaru',
			'Short Stack',
			'Shrikhand',
			'Sigmar One',
			'Signika',
			'Signika Negative',
			'Silkscreen',
			'Simonetta',
			'Sintony',
			'Sirin Stencil',
			'Six Caps',
			'Skranji',
			'Slabo 13px',
			'Slabo 27px',
			'Slackey',
			'Smokum',
			'Smooch Sans',
			'Smythe',
			'Sniglet',
			'Snippet',
			'Snowburst One',
			'Sofadi One',
			'Sofia',
			'Solway',
			'Song Myung',
			'Sonsie One',
			'Sora',
			'Sorts Mill Goudy',
			'Source Code Pro',
			'Source Sans 3',
			'Source Sans Pro',
			'Source Serif 4',
			'Source Serif Pro',
			'Space Grotesk',
			'Space Mono',
			'Special Elite',
			'Spectral',
			'Spectral SC',
			'Spicy Rice',
			'Spinnaker',
			'Spirax',
			'Squada One',
			'Sree Krushnadevaraya',
			'Sriracha',
			'Srisakdi',
			'Staatliches',
			'Stalemate',
			'Stalinist One',
			'Stardos Stencil',
			'Stick',
			'Stick No Bills',
			'Stint Ultra Condensed',
			'Stint Ultra Expanded',
			'Stoke',
			'Strait',
			'Style Script',
			'Stylish',
			'Sue Ellen Francisco',
			'Suez One',
			'Sulphur Point',
			'Sumana',
			'Sunflower',
			'Sunshiney',
			'Supermercado One',
			'Sura',
			'Suranna',
			'Suravaram',
			'Suwannaphum',
			'Swanky and Moo Moo',
			'Syncopate',
			'Syne',
			'Syne Mono',
			'Tajawal',
			'Tangerine',
			'Tapestry',
			'Taprom',
			'Tauri',
			'Taviraj',
			'Teko',
			'Telex',
			'Tenali Ramakrishna',
			'Tenor Sans',
			'Text Me One',
			'Texturina',
			'Thasadith',
			'The Nautigal',
			'Tienne',
			'Tillana',
			'Timmana',
			'Tinos',
			'Titan One',
			'Titillium Web',
			'Tomorrow',
			'Tourney',
			'Trade Winds',
			'Train One',
			'Trirong',
			'Trispace',
			'Trocchi',
			'Trochut',
			'Truculenta',
			'Trykker',
			'Tulpen One',
			'Turret Road',
			'Ubuntu',
			'Ubuntu Condensed',
			'Ubuntu Mono',
			'Uchen',
			'Ultra',
			'Uncial Antiqua',
			'Underdog',
			'Unica One',
			'UnifrakturCook',
			'UnifrakturMaguntia',
			'Unkempt',
			'Unlock',
			'Unna',
			'Urbanist',
			'VT323',
			'Vampiro One',
			'Varela',
			'Varela Round',
			'Varta',
			'Vast Shadow',
			'Vazirmatn',
			'Vesper Libre',
			'Viaoda Libre',
			'Vibes',
			'Vibur',
			'Vidaloka',
			'Viga',
			'Voces',
			'Volkhov',
			'Vollkorn',
			'Vollkorn SC',
			'Voltaire',
			'Waiting for the Sunrise',
			'Wallpoet',
			'Walter Turncoat',
			'Warnes',
			'Water Brush',
			'Waterfall',
			'Wellfleet',
			'Wendy One',
			'WindSong',
			'Wire One',
			'Work Sans',
			'Xanh Mono',
			'Yaldevi',
			'Yanone Kaffeesatz',
			'Yantramanav',
			'Yatra One',
			'Yellowtail',
			'Yeon Sung',
			'Yeseva One',
			'Yesteryear',
			'Yrsa',
			'Yusei Magic',
			'ZCOOL KuaiLe',
			'ZCOOL QingKe HuangYou',
			'ZCOOL XiaoWei',
			'Zen Antique',
			'Zen Antique Soft',
			'Zen Dots',
			'Zen Kaku Gothic Antique',
			'Zen Kaku Gothic New',
			'Zen Kurenaido',
			'Zen Loop',
			'Zen Maru Gothic',
			'Zen Old Mincho',
			'Zen Tokyo Zoo',
			'Zeyada',
			'Zhi Mang Xing',
			'Zilla Slab',
			'Zilla Slab Highlight',
		);

		return apply_filters( 'imm_google_fonts', $fonts );
	}

	public static function getWeights(): array {
		return self::WEIGHTS;
	}

	public static function getSubsets(): array {
		return self::SUBSETS;
	}

	public static function getFontUrl( array $enabledFonts ): string {
		if ( empty( $enabledFonts ) ) {
			return '';
		}

		$families = array();

		foreach ( $enabledFonts as $font => $config ) {
			$family     = str_replace( ' ', '+', $font );
			$weights    = $config['weights'] ?? array( 400, 700 );
			$families[] = $family . ':' . implode( ',', array_map( 'strval', $weights ) );
		}

		$query = 'family=' . implode( '|', $families );
		$query = apply_filters( 'imm_google_fonts_url', $query );

		return 'https://fonts.googleapis.com/css2?' . $query . '&display=swap';
	}
}
